import type { Metadata } from "next";
import "@/app/globals.css";
import { Providers } from "@/app/providers";
import { inter,suwannaphum } from "@/app/fonts";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className='light'>
      <head>
        <link rel="icon" href="favicon.svg" sizes="32x32" type="image/x-icon" />
      </head>
      <body className={` ${inter.variable}  ${suwannaphum.variable} `}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
